language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t clemado1/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true clemado1/react-test-app npm run test

after_success:
  - docker build -t clemado1/docker-frontend ./frontend
  - docker build -t clemado1/docker-backend ./backend
  - docker build -t clemado1/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  
  - docker push clemado1/docker-frontend
  - docker push clemado1/docker-backend
  - docker push clemado1/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-678590436186
  bucket_path: "docker-fullstack-app"
  on:
    branch: main

access_key_id: $AWS_ACCESS_KEY
access_secret_key: $AWS_SECRET_ACCESS_KEY


